### ISSUE TITLE
how to start RemoteStartTransaction 

### ISSUE THREAD

**Issue by jigar-prajapati-xl** [mikuso/ocpp-rpc#38]
Hello @mikuso Can you please help me with this issue
https://stackoverflow.com/questions/75925898/how-to-start-remote-transection-in-ocpp-server-using-node-js

**Comment by mikuso** [comment]
Hi. I've had a shot at answering this for you.

**Comment by vasu-rangpariya-xl** [comment]
@mikuso What the difference between two event `StartTransaction` & `RemoteStartTransaction`. I am confused when should I call which event is there any docs or anything else. Our use case is like we want to start transaction from our external mobile app which will talk to our ocpp server so which event should I call.
Is there any services are available from which we can test our ocpp server who will send us almost same data that we will get from real charging station ?

**Comment by mikuso** [comment]
It sounds like you've got a lot of research to do.

The `RemoteStartTransaction` request is always initiated by the central system - it is an instruction to the charging station to attempt to start a charging session transaction.

The `StartTransaction` request is always initiated by the charging station to inform the central system that it has begun a charging session transaction.

It is not always necessary for the central system to kickstart the charging session via `RemoteStartTransaction`. For instance, the charging station may be configured to simply start whenever a cable is connected (free to use), or it may use a different authentication method such as a payment terminal or RFID card reader local to the device. In these cases, the `RemoteStartTransaction` request is not needed.

In the case of using a mobile app to start the charge, then yes you will need to send a RemoteStartTransaction (via the central system) to the charging station.

All of this is explained via the documentation provided by the OCA. You can download the specs here: https://www.openchargealliance.org/downloads/

The OCA also offer a testing tool which can simulate a charging station. This is called the OCTT - it's quite expensive. It may be cheaper to buy an OCPP-compatible charging station and a vehicle simulator instead. I'm not aware of any other charging station simulators which offer any reasonable level of compatibility with the specs.

**Comment by vasu-rangpariya-xl** [comment]
@mikuso I have one question how can we get information about connector type like ( CCS2 , Mennekes ) from charging station ? I want to get information about which connector types my charging station supports & either it is AC or DC. Is there any method available ?

**Comment by mikuso** [comment]
This is not possible in OCPP1.6 as standard.

If you are interfacing with an OCPP1.6 charging station, you might want to try looking to see if it adds any custom configuration keys which might give you a hint - but honestly I think this is unlikely, and won't help you in the general case anyway.

In OCPP2.0.1 you should be able to get the connector type by using GetBaseReport, so that might be an option for you if your charging station supports it? In this report, SupplyPhases is either 1 or 3 for AC, and 0 for DC. The connector type is revealed in the connector's ConnectorType attribute (see 3.22. ConnectorEnumType in the OCPP2.0.1-part2 specs for the full list of connector types).

**Comment by ZOUHIR23** [comment]
@mikuso hope that you're fine 
i have one question ; is that solution work with browsers it means that 
if there any problems during implementing the csms regarding your solution
because you have mentionned 
""This module is built for Node.js and does not currently work in browsers. '"

**Comment by mikuso** [comment]
Hi @ZOUHIR23,

The module is written in javascript, but cannot be run from within a web browser context. I noted this at the top of the readme because it's a common issue that people try to run this code directly in a web browser by mistake. There are several reasons why it cannot run in a web browser:

1) It's not possible to create a WebSocket server in a web browser context, so a CSMS using this module (or any similar module) directly in the browser cannot be done.
2) The standard browser implementation of WebSockets is not compatible with some aspects of the OCPP-J spec, such as the use of HTTP Basic auth - so any implementation would only ever be part-complete at best.

It may theoretically be possible to offer a limited-compatibility version of the RPCClient to run in browsers, but it wouldn't make sense for an actual charging station to run this code within a web browser.  I can only foresee one use-case for running this in a browser would be if you were creating a charging station simulator, but even in this case it would make more sense (from both a compatibility and security point of view) to make the OCPP connection to the CSMS via a NodeJS back-end, and have a separate front-end client that can interface with this.

I hope this helps.

I'm going to close this issue now as it is drifting far off topic and the original issue appears to be resolved. If you have any other questions, please create a new issue. Thanks.

**Comment by ZOUHIR23** [comment]
@mikuso thanks for your responce
What I understood now is that we can not use this solution with a real charging station ?

**Comment by ZOUHIR23** [comment]
And please 
what did you mean about that **" directly in the browser "**

**Comment by mikuso** [comment]
> @mikuso thanks for your responce What I understood now is that we can not use this solution with a real charging station ?

Incorrect. You can indeed use this with a real charging station. In fact, I can tell you that this module is currently being used in production, powering a CSMS controlling over 10,000 real charging stations of varying manufacturers. So it is perfectly capable of being used in a real-world scenario.

> And please what did you mean about that **" directly in the browser "**

The only issue with compatibility is if you are trying to use this module code within a web browser context. (e.g. trying to run **ocpp-rpc** within Chrome or Firefox)

You see - some people think that because javascript runs in a web browser, that this implies that _all_ javascript modules will run in a web browser. This is _**not**_ the case (especially for this module). The correct way to use this module is with Node.JS, and not within a web browser.

I'm sorry if this has confused you unnecessarily.
